version: '3.9'

services:
  backend:
    image: backend
    build:
      context: Backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: stagging
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysql
    networks:
      - restaurantnet
  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - ./SQL Database/Item.sql:/docker-entrypoint-initdb/0_init.sql
      - $HOME/dump:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - restaurantnet

  frontend:
    image: frontend
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: staging
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - restaurantnet

networks:
  restaurantnet:
    driver: bridge 